@startuml
nwdiag {
  network rigel_internal {
    address = "10.0.10.0/24"
    color = "blue"

    // define groups?
    
    router03 [address = 10.0.10.1/24,, shape = "node"]
    therapon [address = 10.0.10.2/24,, shape = "node"]
    intrus [address = 10.0.10.3/24,, shape = "node"]
    deriweb01 [address = 10.0.10.7/24,, shape = "node"]
    derisql01 [address = 10.0.10.8/24,, shape = "node"]
    philia [address = 10.0.10.10/24,, shape = "node"]
    deriutil01 [address = 10.0.10.11/24,, shape = "node"]
    zeus [address = 10.0.10.14/24,, shape = "node"]
    derigsm01 [address = 10.0.10.18/24,, shape = "node"]
    dericom01 [address = 10.0.10.19/24,, shape = "node"]
    derimisc01 [address = 10.0.10.20/24,, shape = "node"]

  }
  network sun_internal {
    address = "10.0.5.0/24"
    color = "orange"
    

    router04 [address = 10.0.5.1/24, shape = "node"]
    gaia [address = 10.0.5.4/24,, shape = "node"]
    vault [address = 10.0.5.5/24,, shape = "node"]
    mysql01 [address = 10.0.5.6/24,, shape = "node"]
    ns4 [address = 10.0.5.7/24,, shape = "node"]
    mx2 [address = 10.0.5.8/24,, shape = "node"]


  }
  network home_internal {
    address = "192.168.20.0/24"
    color = "palegreen"
    

    opaon[address = 192.168.20.3/24, shape = "node"]
    kvm01 [address = 192.168.20.31/24, shape = "node"]
    kvm02 [address = 192.168.20.31/24/24,, shape = "node"]


  }
}
@enduml
